#pragma once
#include "Versioning.h" // this file is generated by CMAKE during build process
// ------------Audio -----------------
const float g_desired_blocksize_ms(2); // its in ms to be independent from the sampling rate
const bool g_forcePowerOf2(false); // should be true for FFT Processing

// -------------- GUI -----------------
// global GUI setting for StereoAnalyzer
// squarer than the template default: the goniometer needs a roughly square area
const int g_minGuiSize_x(560);
const int g_maxGuiSize_x(1200);
const int g_minGuiSize_y(470);
const float g_guiratio = float(g_minGuiSize_y)/g_minGuiSize_x;

// ---------- presethandler ----------
//const StringArray g_PresetCategories("Unknown", "Lead", "Brass", "Template", "Bass",
//	"Key", "Organ" , "Pad", "Drums_Perc", "SpecialEffect","Sequence", "String" );
const juce::StringArray g_PresetCategories(""); // keep empty for "no categories"

const int g_minPresetHandlerHeight(30); // in pixels
#define MIN_COMBO_WITH_PRESET 120
#define MIN_ELEMENT_DIST_PRESET 10
#define MIN_BUTTON_WIDTH_PRESET 40
#define MIN_ELEMENT_HEIGHT_PRESET 20

// ------- Midi Keyboard display-------
const float g_midikeyboardratio(0.13f); // in percent of height()
const float g_wheelstokeyboardratio(0.1f);

// -------Your defines for GUI --------
// layout of StereoAnalyzerGUI::resized() (all in pixels, at scaleFactor 1.0)
const int g_settingsButtonSize(20);       // small square gear-icon button, no dedicated row of
const int g_settingsButtonMargin(2);      // its own -- see resized(), it sits in the Levels
                                           // panel's own top-left corner instead

const int g_correlationRowHeight(56);     // bottom row: title + bar + endpoint labels
const int g_correlationPaddingX(4);       // gap between the correlation panel and its neighbours
const int g_correlationPaddingY(2);

const int g_levelMeterMaxWidth(190);      // level meter panel: min(this, remaining width / divisor)
const int g_levelMeterWidthDivisor(4);
const int g_levelMeterPadding(2);

const int g_goniometerPadding(4);         // goniometer fills whatever remains

