#pragma once
#include "Versioning.h" // this file is generated by CMAKE during build process
// ------------Audio -----------------
const float g_desired_blocksize_ms(2); // its in ms to be independent from the sampling rate
const bool g_forcePowerOf2(false); // should be true for FFT Processing

// -------------- GUI -----------------
// global GUI setting for StereoWidener
const int g_minGuiSize_x(480);
const int g_maxGuiSize_x(1200);
// meterRow (260) + rowGap (8) + the taller of the three control columns below it
// (currently the middle one: Width label+knob+textbox 146, + rowGap 8 + algorithm row
// 30, + rowGap 8 + mono-safe badge 18 = 210, see the layout constants below) + 31 for
// the preset control reserved above it (g_minPresetHandlerHeight = 30, plus the 1px gap
// PluginEditor.cpp's resized() adds) now that WITH_PRESETHANDLERGUI is enabled
// (StereoWidener/CMakeLists.txt) -- without this, the preset bar simply ate into
// StereoWidenerGUI's own height instead of the window growing to fit both, pushing the
// algorithm selector below the visible window -- with a small margin. Substantially
// shorter than before the Phase 5 GUI compaction (was 685): Utilities used to be its
// own set of full-width rows below the algorithm selector; it is now a third column
// alongside Width and the aux knobs, stacked below the output meter instead (every
// utility acts on the final output signal), so it adds no height of its own as long as
// it fits within the middle column's height -- see g_util* below.
const int g_minGuiSize_y(520);
const float g_guiratio = float(g_minGuiSize_y)/g_minGuiSize_x;

// ---------- presethandler ----------
const juce::StringArray g_PresetCategories(""); // keep empty for "no categories"

const int g_minPresetHandlerHeight(30); // in pixels
#define MIN_COMBO_WITH_PRESET 120
#define MIN_ELEMENT_DIST_PRESET 10
#define MIN_BUTTON_WIDTH_PRESET 40
#define MIN_ELEMENT_HEIGHT_PRESET 20

// ------- Midi Keyboard display-------
const float g_midikeyboardratio(0.13f); // in percent of height()
const float g_wheelstokeyboardratio(0.1f);

// -------Your defines for GUI --------
// layout of StereoWidenerGUI::resized(), all in pixels at scaleFactor 1.0. The meter
// row (input level meter / goniometer / output level meter) is sized to about 60% of
// what the same meters look like in StereoAnalyzer, since the widener also needs room
// below for the width knob and the algorithm selector.
const int g_meterRowHeight(260);          // height of the input/goniometer/output row
const int g_levelMeterWidth(115);         // fixed width for each side level meter (~60% of
                                           // StereoAnalyzer's g_levelMeterMaxWidth = 190)
const int g_levelMeterPadding(2);
const int g_goniometerPadding(4);
const juce::Colour g_goniometerInColour(juce::Colours::limegreen);  // input series
const juce::Colour g_goniometerOutColour(juce::Colours::deepskyblue); // output series

const int g_rowGap(8);                    // vertical gap between the three stacked rows

// Below the meter row sit three columns, left-edge-aligned with the input meter and
// right-edge-aligned with the output meter respectively (StereoWidenerGUI::resized()):
// left = the two aux knobs stacked vertically, middle = Width + the algorithm selector
// + the mono-safe badge, right = Utilities. All three are top-anchored and vertically
// centred within the tallest column's own height (currently the middle one).

const int g_widthKnobSize(110);           // diameter of the big Width rotary knob
const int g_widthKnobLabelHeight(18);

// Aux knobs (left column): stacked vertically now (Phase 5 GUI compaction moved the
// second one here from the right of Width, to make room for Utilities below the output
// meter) -- their meaning depends on the active algorithm, see StereoAlgorithm::
// getAuxLeftInfo()/getAuxRightInfo().
const int g_auxKnobSize(64);
const int g_auxKnobLabelHeight(16);
const int g_auxKnobVGap(10);              // vertical gap between the two stacked aux knobs

const int g_algorithmRowHeight(30);
const int g_algorithmBoxWidth(260);
const int g_helpButtonSize(22);           // small square "?" button, left of the algorithm box
const int g_helpButtonGap(6);
const int g_algorithmHelpPanelWidth(340);

// "Not mono-safe" badge (Phase 5 step 4), directly below the algorithm selector row --
// visible only when the active algorithm's isMonoSafe() is false (first needed by
// algorithm 2.5, AllpassDecorrelation). Always reserved in the layout (empty text when
// not shown) so switching algorithms never shifts anything below it.
const int g_monoSafeBadgeHeight(18);

// Utilities (Phase 4 step 2: planing.md 2.13 + 2.2; moved into its own column below the
// output meter in Phase 5's GUI compaction, since every utility acts on the final
// output signal -- see UtilityProcessor.h). Rotation/Balance knobs on top, then a
// caption, the three toggle buttons, another caption, then the Monitor selector --
// every widget in this column shares g_utilColumnWidth, so the Monitor box and the two
// toggle/knob rows are all centred within (and the Monitor box exactly fills) the same
// width.
const int g_utilColumnWidth(150);
const int g_utilKnobSize(48);
const int g_utilKnobLabelHeight(14);
const int g_utilKnobGap(12);              // horizontal gap between Rotation and Balance knobs
const int g_utilCaptionHeight(14);        // "Flip" above the toggle buttons, "Monitor" above the combo box
const int g_utilToggleRowHeight(24);
const int g_utilToggleWidth(44);          // Swap / Inv L / Inv R buttons
const int g_utilToggleGap(6);
const int g_utilMonitorBoxHeight(22);
