#pragma once
#include "Versioning.h" // this file is generated by CMAKE during build process
// ------------Audio -----------------
const float g_desired_blocksize_ms(2); // its in ms to be independent from the sampling rate
const bool g_forcePowerOf2(false); // should be true for FFT Processing

// -------------- GUI -----------------
// global GUI setting for StereoWidener
const int g_minGuiSize_x(480);
const int g_maxGuiSize_x(1200);
// 456 for StereoWidenerGUI's own content (meterRow 260 + rowGap 8 + knobRow 150 +
// rowGap 8 + algorithmRow 30, see the layout constants below) + 31 for the preset
// control now reserved above it (g_minPresetHandlerHeight = 30, plus the 1px gap
// PluginEditor.cpp's resized() adds) now that WITH_PRESETHANDLERGUI is enabled
// (StereoWidener/CMakeLists.txt) -- without this, the preset bar simply ate into
// StereoWidenerGUI's own height instead of the window growing to fit both, pushing the
// algorithm selector below the visible window.
const int g_minGuiSize_y(491);
const float g_guiratio = float(g_minGuiSize_y)/g_minGuiSize_x;

// ---------- presethandler ----------
const juce::StringArray g_PresetCategories(""); // keep empty for "no categories"

const int g_minPresetHandlerHeight(30); // in pixels
#define MIN_COMBO_WITH_PRESET 120
#define MIN_ELEMENT_DIST_PRESET 10
#define MIN_BUTTON_WIDTH_PRESET 40
#define MIN_ELEMENT_HEIGHT_PRESET 20

// ------- Midi Keyboard display-------
const float g_midikeyboardratio(0.13f); // in percent of height()
const float g_wheelstokeyboardratio(0.1f);

// -------Your defines for GUI --------
// layout of StereoWidenerGUI::resized(), all in pixels at scaleFactor 1.0. The meter
// row (input level meter / goniometer / output level meter) is sized to about 60% of
// what the same meters look like in StereoAnalyzer, since the widener also needs room
// below for the width knob and the algorithm selector.
const int g_meterRowHeight(260);          // height of the input/goniometer/output row
const int g_levelMeterWidth(115);         // fixed width for each side level meter (~60% of
                                           // StereoAnalyzer's g_levelMeterMaxWidth = 190)
const int g_levelMeterPadding(2);
const int g_goniometerPadding(4);
const juce::Colour g_goniometerInColour(juce::Colours::limegreen);  // input series
const juce::Colour g_goniometerOutColour(juce::Colours::deepskyblue); // output series

const int g_rowGap(8);                    // vertical gap between the three stacked rows

const int g_widthKnobSize(110);           // diameter of the big Width rotary knob
const int g_widthKnobRowHeight(150);      // reserved height for knob + its label/textbox
const int g_widthKnobLabelHeight(18);

const int g_auxKnobSize(64);              // diameter of the two smaller flanking knobs
const int g_auxKnobLabelHeight(16);       // (their meaning depends on the active algorithm,
const int g_auxKnobGap(16);               // see StereoAlgorithm::getAuxLeftInfo()/getAuxRightInfo())

const int g_algorithmRowHeight(30);
const int g_algorithmBoxWidth(260);
const int g_helpButtonSize(22);           // small square "?" button, left of the algorithm box
const int g_helpButtonGap(6);
const int g_algorithmHelpPanelWidth(340);
